USE [master]
GO

-- ********** For Development ************
CREATE DATABASE [TradeLite] ON  PRIMARY 
( NAME = N'TradeLite_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TradeLite_Data.mdf' , SIZE = 1048576KB , MAXSIZE = 2097152KB , FILEGROWTH = 262144KB  )
 LOG ON 
( NAME = N'TradeLite_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TradeLite_Log.ldf' ,  SIZE = 524288KB , MAXSIZE = 1048576KB , FILEGROWTH = 262144KB)
-- ********** For Development ************

-- ********** For Halyk ************
--CREATE DATABASE [TradeLite] ON  PRIMARY 
--( NAME = N'TradeLite_Data', FILENAME = N'E:\MSSQL\Data\TradeLite_Data.mdf' , SIZE = 1048576KB , MAXSIZE = 2097152KB , FILEGROWTH = 262144KB  )
-- LOG ON 
--( NAME = N'TradeLite_Log', FILENAME = N'E:\MSSQL\Data\TradeLite_Log.ldf' ,  SIZE = 524288KB , MAXSIZE = 1048576KB , FILEGROWTH = 262144KB)
-- ********** For Halyk ************

GO
ALTER DATABASE [TradeLite] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [TradeLite] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TradeLite] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TradeLite] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TradeLite] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TradeLite] SET ARITHABORT OFF 
GO
ALTER DATABASE [TradeLite] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TradeLite] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TradeLite] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TradeLite] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TradeLite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TradeLite] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TradeLite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TradeLite] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TradeLite] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TradeLite] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TradeLite] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TradeLite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TradeLite] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TradeLite] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TradeLite] SET  READ_WRITE 
GO
ALTER DATABASE [TradeLite] SET RECOVERY FULL 
GO
ALTER DATABASE [TradeLite] SET  MULTI_USER 
GO
ALTER DATABASE [TradeLite] SET PAGE_VERIFY CHECKSUM  
GO

USE [TradeLite]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') 
  ALTER DATABASE [TradeLite] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

RECONFIGURE

